### PR TITLE
Title name Update

### PR DESCRIPTION
**Pull request by agentz101**
I added Title Names for each webpage on our website, as well as a unit test to check that the title is updated.  I also added vue-meta and vuex for development.

### CODE REVIEW

**Comment by BettridgeKameron** [comment]
I will have to add this after merging Ray's, since you have the text rephrase (otherwise, his request would remove your title stuff!)
1. Can you make your js test ts instead of js? If your lazy converters exist online, but everyone else is using typescript, and this will mess with automation and integration later when I implement it.
2. Ill look into it more later, but you may be overcomplicating the title as I believe you don't need to make a title component, as if you're using vuemeta im pretty sure its just
```
metaInfo() {
        return { 
            title: "title is put here"
         }
   }
```
Otherwise, vuemeta becomes not needed. Check docs here: https://vue-meta.nuxtjs.org/api/#title

**Comment by agentz101** [comment]
Why can it not be JS?  It works the npm run test:unit, so what would specifically cause the conflict?

**Comment by agentz101** [comment]
I have changed it to TS and linted it.

**Comment by BettridgeKameron** [comment]
the TS Looks great @agentz101, nice work! 

There are some branch conflicts for some reason, which implies some issues with development. See if you can check that out, as we are unable to merge with it in this state (which you can see below)

The second thing still applies however, as you shouldn't need an entire TitleComponent and can just add something like the following example from [Digital Ocean's Vue Meta Tutorial here](https://www.digitalocean.com/community/tutorials/vuejs-vue-meta)
```
export default {
  name: 'App',
  metaInfo: {
    title: 'Default App Title',
    titleTemplate: '%s | vue-meta Example App',
    htmlAttrs: {
      lang: 'en-US'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'description', content: 'An example Vue application with vue-meta.' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' }
    ]
  },
  // ...
}
```
To each file, which has the benefits of:
1. Simplifies your code, and lessens it (no more need for title component)
2. Reduces possibility of errors
3. Allows us to have the other metadata options outside of just the title, therefore more modularity
4. Going off 2. once we added the other metadata, we would either have had to modify your TitleComponent fully to support other things (entire refactor), or just go with the Digital Ocean example aproach


Do you think you would be able to take this approach instead, and also add some other metadata too that may be important? Such as:
- charset
- description
- viewport
- opengraph if you want to be fancy (this is how websites control how they look when embeded in things like social media)
  - This is things like og:title, og:url, og:description, and og:image
- robots, to make sure only the homepage is indexed, but none of the other pages

If you want, I can also do this for you, if you wish to do something else.

**Pull request merged**
